---
title: "R Notebook"
output: html_notebook
---

# 1. Introduction

Analyses file for the `CodeClan - dirty data project - task 4: Halloween Candy
Thijmen Breeschoten 
CodeClan Professional Data Analysis student cohort DE21
This file does provide information regarding the cleaning/analyses steps taken for 
the 'Dirty Data' project Halloween Candy.

# 2. Overview

Goal of the project task is to clean and analyse a raw dataset in order to answer 
several questions regarding the data.
The raw data contains results from a questionnaire regarding halloween/trick or treat candy.
The questionnaires are taken in three consecutive years (2015, 2016, 2017), and
the results can be found in three separate .xlsx files:
- `boing-boing-candy-2015.xlsx`
- `boing-boing-candy-2016.xlsx`
- `boing-boing-candy-2017.xlsx`

Contents of this file:
1. Introduction
2. Overview
3. Language, software and packages used
4. File and folder overview
5. cleaning overview
6. Assumptions / decisions
7. analyses overview & answers

# 3. Language, software and packages used

* The code is written in R (version 4.3.0)
  R Core Team (2023). _R: A Language and Environment for Statistical Computing_. 
  R Foundation for Statistical Computing, Vienna, Austria.
   <https://www.R-project.org/>

* R is run in Rstudio 2023.03.0+386 

* The following libraries are required (specified per script):
  cleaning_candy.R
  - `tidyverse`(ver 2.0.0)
  - `readxl` (ver 1.4.2)
  analysing_candy.Rmd
  - `tidyverse`(ver 2.0.0)
  
# 4. File and folder overview
The Rproject folder `halloween_candy` contains the .Rproj file and the following 
folders.
The following files are included and distributed in each folder:

clean_data
  - `candy_cleaned.csv` cleaned dataset using script 'cleaning_candy.R'
data_cleaning_scripts
  - `cleaning_candy.R` Rscript to read and clean the raw data file.
documentation_and_analysis
  - `analysing_candy.Rmd` (and knitted html file) Rnotebook script presenting an 
  overview and background information regarding the project and analyses. It further   presents the script/code to analyse the cleaned dataset in order to answer the       analyses questions.
raw_data
  - ``boing-boing-candy-2015.xlsx`, `boing-boing-candy-2016.xlsx`,                       `boing-boing-candy-2017.xlsx` raw datasets in xlsx format.
  
# 5. cleaning overview